# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/eikon/all/eikon.rbi
#
# eikon-0.1.0

module Eikon
  def self.dhash_for_file(*args, ****, &blk); end
  def self.distance_between_files(*args, ****, &blk); end
  def self.process_video(*args, ****, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Eikon::Error < StandardError
end
