# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/eikon/all/eikon.rbi
#
# eikon-0.1.0

module Eikon
end
class Eikon::VideoProcessor
  def filename; end
  def initializer(filename); end
end
